baseURL = '$HOSTNAME$/'
title = 'Lieuwe Leene'
languageCode = 'en-uk'
theme = 'hermit'
relativeURLs = true
canonifyURLs = true

enableGitInfo = true
pygmentsCodefences  = true
pygmentsUseClasses  = true
hasCJKLanguage = true
rssLimit = 10
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
enableEmoji = true

themeColor = "#494f5c"

[taxonomies]
  tag = "tags"

[params]
  dateform        = 'Jan 2, 2006'
  dateformShort   = 'Jan 2'
  dateformNum     = '2006-01-02'
  dateformNumTime = '2006-01-02 15:04 -0700'
  homeSubtitle    = "Welcome Friend"

[author]
  name = 'L. B. Leene'

[[params.social]]
  name = 'linkedin'
  url = 'https://www.linkedin.com/in/lleene/'

[[params.social]]
  name = 'twitter'
  url = 'https://twitter.com/LieuweLeene'

[[params.social]]
  name = 'email'
  url = 'mailto:lieuwe@leene.dev'

[[params.social]]
  name = "github"
  url = "https://git.leene.dev/lieuwe"

[menu]
  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 2
  [[menu.main]]
    name = "Publications"
    url = "publications/"
    weight = 3
  [[menu.main]]
    name = "Chips"
    url = "chips/"
    weight = 5
  [[menu.main]]
    name = "Resume"
    url = "resume/"
    weight = 10
